name: Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up .Net 10.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.X
      
      - name: Run Server Tests
        run: cd Server.Tests && dotnet build && bin/Debug/net10.0/Server.Tests --coverage --coverage-output-format cobertura --coverage-settings config.runsettings
        
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "*.Tests/**/TestResults/**/*.cobertura.xml"
          badge: false
          fail_below_min: true
          format: text
          hide_branch_rate: true
          hide_complexity: true
          indicators: false
          thresholds: '80 90'