name: Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          echo "docker compose -f compose.build-test.yaml build"
          docker compose -f compose.build-test.yaml build
      
      - name: Copy test executables from image
        run: |
          docker create --name tests hm-user-service-test
          docker cp tests:/app/publish-test ./Server.Tests/publish-test
          docker rm -f tests
      
      - name: Run tests
        run: ./Server.Tests/publish-test/Server.Tests --coverage --coverage-output-format cobertura --coverage-settings Server.Tests/config.runsettings
        
      - name: Code Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: "*.Tests/**/TestResults/**/*.cobertura.xml"
          minimum_coverage: 80
          fail_below_threshold: true
          skip_covered: false
          show_class_names: true